var scheme_arr={
	"1":"INDRADHANUSH",
	"2":"KRISHI AMDANI BIMA YOJANA",
	"3":"JANANI SURAKSHA YOJANA",
	"4":"WEATHER BASED CROP INSURANCE",
	"5":"NATIONAL HORTICULTURE MISSION",
	"6":"AAM ADMI BIMA YOJANA",
}